name: Codeowners Validator

on:
  workflow_dispatch:
  pull_request:

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v3

      - uses: mszostok/codeowners-validator@v0.7
        if: github.event.pull_request.head.repo.full_name == github.repository
        name: "Full check of CODEOWNERS"
        with:
          checks: "files,syntax,owners,duppatterns"
          experimental_checks: "notowned,avoid-shadowing"
          owner_checker_allow_unowned_patterns: "false"
          github_access_token: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"

      - uses: mszostok/codeowners-validator@v0.7
        if: github.event.pull_request.head.repo.full_name != github.repository
        name: "Syntax check of CODEOWNERS"
        with:
          checks: "syntax,duppatterns"
          owner_checker_allow_unowned_patterns: "false"
